### ISSUE TITLE
Live demo broken

### ISSUE THREAD

**Issue by xinaesthete** [leapmotion/leapjs-widgets#5]
Seems like the subdomain js.leapmotion.com is offline.

**Comment by RecursiveCptHook** [comment]
https://github.com/leapmotion/leapjs/issues/229#issuecomment-616845403

>The https://js.leapmotion.com CDN should be back up and working as expected.
>
> Version 0.6.4 is available at https://js.leapmotion.com/leap-0.6.4.min.js
>
> Version 1.0.0 is not yet available on NPM but is also available at https://js.leapmotion.com/leap-1.0.0.min.js
